// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATVk_B_wcVyg2mqzcL2x_itxNADXZbZhw',
    appId: '1:583238683026:web:0c5b4dd1d380c058ae994b',
    messagingSenderId: '583238683026',
    projectId: 'resieasy-6ac13',
    authDomain: 'resieasy-6ac13.firebaseapp.com',
    storageBucket: 'resieasy-6ac13.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ETkjGHnB_RE-QhM_01ANDjSdxPG3VmM',
    appId: '1:583238683026:android:6b5e2343821a70a2ae994b',
    messagingSenderId: '583238683026',
    projectId: 'resieasy-6ac13',
    storageBucket: 'resieasy-6ac13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6PUU9vhnReaBVCGhxKQIrS3DkPWqycMA',
    appId: '1:583238683026:ios:717b6fb06cf13b05ae994b',
    messagingSenderId: '583238683026',
    projectId: 'resieasy-6ac13',
    storageBucket: 'resieasy-6ac13.firebasestorage.app',
    iosBundleId: 'com.example.apartmentManagerUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6PUU9vhnReaBVCGhxKQIrS3DkPWqycMA',
    appId: '1:583238683026:ios:717b6fb06cf13b05ae994b',
    messagingSenderId: '583238683026',
    projectId: 'resieasy-6ac13',
    storageBucket: 'resieasy-6ac13.firebasestorage.app',
    iosBundleId: 'com.example.apartmentManagerUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATVk_B_wcVyg2mqzcL2x_itxNADXZbZhw',
    appId: '1:583238683026:web:f8756304ef5e2a9eae994b',
    messagingSenderId: '583238683026',
    projectId: 'resieasy-6ac13',
    authDomain: 'resieasy-6ac13.firebaseapp.com',
    storageBucket: 'resieasy-6ac13.firebasestorage.app',
  );

}